<?php

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\node\NodeInterface;
use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_help().
 */
function hello_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {

    // Main module help for the hello module.
    case 'help.page.hello':
      return '<p>'. t('Hello module\'s help page.') . '</p>';
  }
}

/**
 * Implements hook_cron().
 */
function hello_cron() {
  drupal_set_message(t('Hello module cron task done.'), 'warning');
}

/**
 * Implements hook_user_login().
 */
function hello_user_login($account) {
  drupal_set_message(t('Welcome dear %name !', ['%name' => $account->getAccountName()]));
}

/**
 * Implements hook_node_update().
 * @param \Drupal\node\NodeInterface $node
 * @throws Exception
 */
function hello_node_update(NodeInterface $node) {

    $user = \Drupal::currentUser();
    $nid = $node->id();
    $update_time = $node->getChangedTime();
    $uid = $user->id();

    $database = \Drupal::database();
    $database->insert('hello_node_history')
        ->fields([
            'nid' => $nid,
            'update_time' =>$update_time,
            'uid' => $uid,
        ])
        ->execute();

}

/**
 * Implements hook_node_delete().
 * @param \Drupal\node\NodeInterface $node
 */
function hello_node_delete(NodeInterface $node) {

    $nid = $node->id();
    $database = \Drupal::database();
    $database->delete('hello_node_history')
        ->condition('nid', $nid)
        ->execute();
}

function hello_preprocess_block(array &$variables) {
    $class = \Drupal::config('hello.config')->get('color');
    $variables['attributes']['class'][] = $class;
}

function hello_page_attachments(array &$page) {
    $page['#attached']['library'][] = 'hello/base';
}

function hello_theme($existing, $type, $theme, $path) {
    return array(
        'hello_node_history' => array(
            'template' => 'hello_node_history',
            'variables' =>array(
                'node' => NULL,
                'count' => NULL,
            ),
        ),
    );
}

function hello_form_alter(&$form, FormStateInterface $form_state, $form_id) {
    /*if (isset($form['type']) && $form['type']['#value'] . '_node_settings' == $form_id) {
        $upload_enabled_types = \Drupal::config('mymodule.settings')
            ->get('upload_enabled_types');
        $form['workflow']['upload_' . $form['type']['#value']] = [
            '#type' => 'radios',
            '#title' => t('Attachments'),
            '#default_value' => in_array($form['type']['#value'], $upload_enabled_types) ? 1 : 0,
            '#options' => [
                t('Disabled'),
                t('Enabled'),
            ],
        ];

        // Add a custom submit handler to save the array of types back to the config file.
        $form['actions']['submit']['#submit'][] = 'mymodule_upload_enabled_types_submit';
    }*/
    if($form_id == 'contact_message_feedback_form') {

        $form['telephone'] = [
            '#type' => 'tel',
            '#title' => t('Téléphone'),
            '#weight' => -10,
        ];

        $form['actions']['submit']['#value'] = t('Send message now');

        $index = array_search('::save', $form['actions']['submit']['#submit']);
        array_splice($form['actions']['submit']['#submit'], $index, 0, ['my_callback_function']);

        //$form['actions']['submit']['#submit'][]='my_callback_function';

        $form['subject']['#access'] =  FALSE;

    }

}


function my_callback_function(&$form, $form_state) {
    $message = $form_state->getFormObject()->getEntity();
    $message->telephone = $form_state->getValue('telephone');
    //$form['message']['widget']['0']['value']['#value'] = 'JG';
    //ksm($form);
}

function hello_mail_alter(&$message){
    ksm($message);
    if ($message['id'] == 'contact_page_mail') {
        $message['body'][] = $message['params']['contact_message']->telephone;
        ksm($message['params']['contact_message']->telephone);

        ksm($message);
    }

}